name: Test Docker Setup

on:
    push:
        branches: [main]
jobs:
    docker-test:
        runs-on: ubuntu-latest

        steps:
            - name:  Checkout Repository
              uses:  actions/checkout@v3

            - name:  Validate Docker Compose file
              run: docker compose -f docker-compose.yml config

            - name: Start containers
              run: |
                docker compose -f docker-compose.yml up -d --build
                echo "Waiting for services to start..."
                sleep 15

            - name: Check running containers
              run: docker ps

            - name: Stop containers
              if: always()
              run: docker compose -f docker-compose.yml down
